extends: google
env:
  browser: false
  node: true
  es6: true
rules:
  max-len:
  - error
  - code: 120
  require-jsdoc:
  - error
  - require:
      FunctionDeclaration: true
      MethodDefinition: false
      ClassDeclaration: false
      ArrowFunctionExpression: false